(function(root){
 const defaults={priceA:120,priceC:250,downA:20,downC:20,rateA:2.6,rateC:2.6,repaymentA:0,repaymentC:0,term:30,fitA:20,fitC:4,buyA:0,buyC:0,annualA:0,annualC:0,sale:0,cpi:1,depreciation:2,growth:-1,returnRate:2,income:20,initialCash:60,living:8,years:20};
 function validate(p){for(const key of ['repaymentA','repaymentC'])if(![0,1].includes(p[key]))throw Error('请选择有效还款方式');for(const [key,v] of Object.entries(p)){if(!Number.isFinite(v))throw Error('请输入有效数字');} for(const k of ['priceA','priceC','income'])if(p[k]<=0)throw Error('房价和年收入须大于零');for(const k of ['downA','downC'])if(p[k]<0||p[k]>100)throw Error('首付比例须在 0–100% 之间');for(const k of ['rateA','rateC','fitA','fitC','buyA','buyC','annualA','annualC','sale','depreciation','initialCash','living'])if(p[k]<0)throw Error('费用、利率和折旧率不能为负');if(p.term<1||p.term>40||!Number.isInteger(p.term)||p.years<1||p.years>40||!Number.isInteger(p.years))throw Error('贷款期限、居住年限须为 1–40 的整数');for(const k of ['growth','cpi','returnRate'])if(p[k]<=-100)throw Error('年变化率须大于 −100%');if(p.sale>100)throw Error('出售费用比例不能超过 100%');return p;}
 function loan(price,down,rate,term,N,method=0){
  const L=price*(1-down/100),i=rate/1200,t=term*12,k=Math.min(N*12,t),fixed=i?L*i/(1-(1+i)**-t):L/t;
  const payments=Array.from({length:t},(_,m)=>method===1?L/t+(L-m*L/t)*i:fixed);
  const paid=payments.slice(0,k).reduce((sum,v)=>sum+v,0);
  const balance=k===t?0:method===1?L*(1-k/t):i?L*(1+i)**k-fixed*((1+i)**k-1)/i:L-fixed*k;
  return{principal:L,payment:payments[0],lastPayment:payments[t-1],monthlyDecrease:method===1?L/t*i:0,payments,balance:Math.max(0,balance),paid,interest:paid-L+Math.max(0,balance),months:k,method};
 }
 function result(p,N){const a=loan(p.priceA,p.downA,p.rateA,p.term,N,p.repaymentA),c=loan(p.priceC,p.downC,p.rateC,p.term,N,p.repaymentC);const cpi=(1+p.cpi/100)**N-1,repurchase=p.priceA*(1-N*p.depreciation/100+cpi),resale=p.priceC*(1+p.growth/100)**N,saleFee=resale*p.sale/100;const initA=p.priceA*p.downA/100+p.fitA+p.buyA,initC=p.priceC*p.downC/100+p.fitC+p.buyC;const costA=initA+a.paid+p.annualA*N+a.balance-repurchase,costC=initC+c.paid+p.annualC*N+c.balance-resale+saleFee;const base=p.priceC+p.fitC+p.buyC-p.priceA-p.fitA-p.buyA,interest=c.interest-a.interest,annual=(p.annualC-p.annualA)*N,exit=repurchase-resale;
 const q=(1+p.returnRate/100)**(1/12)-1;let savings=(initC-initA)*(1+q)**(12*N);for(let m=1;m<=12*N;m++)savings+=((m<=c.months?c.payments[m-1]:0)-(m<=a.months?a.payments[m-1]:0)+(p.annualC-p.annualA)/12)*(1+q)**(12*N-m);const wealth=savings+repurchase-a.balance-(resale-saleFee-c.balance);const target=(p.priceC+p.fitC+p.buyC+c.interest+p.annualC*N-costA)/(1-p.sale/100),breakGrowth=target>0&&Number.isFinite(target)?((target/p.priceC)**(1/N)-1)*100:null;return{N,a,c,repurchase,resale,saleFee,initA,initC,costA,costC,difference:costC-costA,base,interest,annual,exit,wealth,breakGrowth,target};}
 function assets(p,N,r){function account(init,mortgage,holding,exit){let cash=p.initialCash-init,min=cash;const q=(1+p.returnRate/100)**(1/12)-1;for(let m=1;m<=N*12;m++){cash+=Math.max(cash,0)*q+(p.income-p.living-holding)/12-(m<=mortgage.months?mortgage.payments[m-1]:0);min=Math.min(min,cash);}return{cash,min,net:cash+exit,feasible:min>=-1e-8};}return{a:account(r.initA,r.a,p.annualA,r.repurchase-r.a.balance),c:account(r.initC,r.c,p.annualC,r.resale-r.saleFee-r.c.balance)};}
 const api={defaults,validate,loan,result,assets};if(typeof module!=='undefined')module.exports=api;root.HousingModel=api;
})(typeof globalThis!=='undefined'?globalThis:this);
